name: Build and Test
on: [push]
jobs:
  build-test:
    strategy:
      matrix:
        os:
          - windows-2022
          - ubuntu-24.04
        compiler:
          - clang
          - gcc
          - vs2022
        exclude:
          - os: ubuntu-24.04
            compiler: vs2022
          - os: windows-2022
            compiler: gcc
          - os: windows-2022
            compiler: clang
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install Packages
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install build-essential git make \
               gnome-desktop-testing libasound2-dev libpulse-dev \
               libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
               libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev \
               libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
               libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev

      - name: Build and test (Windows)
        if: runner.os == 'Windows'
        run: cmake --workflow --preset ci-windows-${{ matrix.compiler }}-cl-ninja-test

      - name: Build and test (Linux)
        if: runner.os != 'Windows'
        run: cmake --workflow --preset ci-linux-${{ matrix.compiler }}-ninja-test
