name: Clang Tidy
on: [push]
jobs:
  static-analysis:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install build-essential git make \
               gnome-desktop-testing libasound2-dev libpulse-dev \
               libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
               libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev \
               libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
               libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev

      - run: cmake --workflow --preset ci-check-clang-tidy
